smoke_case_test!(
    internal_compiler_replays_from_bibliography_input_checkpoint_for_semantically_equal_multi_bibliography_edit_with_later_trailing_input_change_with_included_body_with_reversed_dirty_order,
    run_inc_body_replay(IncBodyReplay::Reversed)
);
