smoke_case_test!(
    internal_compiler_falls_back_to_preamble_replay_when_unreadable_dirty_file_precedes_semantically_equal_bibliography_edit_with_included_body,
    run_body_sem_eq_case(BodySemEqCase::UnreadablePrecedes)
);
