smoke_case_test!(
    internal_compiler_falls_back_to_preamble_replay_when_semantically_equal_bibliography_edit_with_later_trailing_input_change_is_followed_by_untracked_dirty_file,
    run_trail_sem_eq_case(TrailSemEqCase::UntrackedFollows)
);
