smoke_case_test!(
    internal_compiler_falls_back_to_preamble_replay_when_unreadable_dirty_file_precedes_semantically_equal_multi_bibliography_edit_with_earlier_input_change_with_included_body,
    run_replay_body_cp_noise(ReplayBodyCpNoise::UnreadablePrecedes)
);
