smoke_case_test!(
    internal_compiler_rebuilds_from_base_for_late_semantic_same_page_multi_bibliography_change_with_later_trailing_input_change_when_unchanged_sibling_bibliography_is_also_dirty_with_other_interleaved_dirty_order_and_untracked_dirty_file_follows,
    run_root_sib(RootSib::OtherInterleavedUntrackedFollows)
);
