smoke_case_test!(
    internal_compiler_rebuilds_from_base_snapshot_for_semantic_multi_bibliography_edit_even_with_later_tracked_input_change_in_fixture_branch_when_unchanged_sibling_bibliography_is_also_dirty_with_interleaved_dirty_order,
    run_tt_sib_order(TtSibOrder::Interleaved)
);
