smoke_case_test!(
    internal_compiler_still_replays_semantically_equal_same_page_multi_bibliography_edit_with_later_trailing_input_change_when_unchanged_sibling_bibliography_is_also_dirty_and_untracked_dirty_file_precedes_it,
    run_sibling_extra_case(SiblingExtraCase::UntrackedDirtyPrecedes)
);
