smoke_case_test!(
    internal_compiler_rebuilds_from_base_snapshot_for_semantic_multi_bibliography_edit_even_with_later_tracked_input_change_in_fixture_branch_when_unchanged_sibling_bibliography_is_also_dirty_with_other_interleaved_dirty_order_and_unreadable_dirty_file_follows,
    run_tt_ord(TtOrd::OtherInterleavedUnreadableFollows)
);
