smoke_case_test!(
    internal_compiler_rebuilds_from_base_snapshot_for_semantic_multi_bibliography_edit_even_with_later_tracked_input_change_in_fixture_branch_when_untracked_dirty_file_precedes,
    run_tt_base(TtBase::UntrackedPrecedes)
);
