include!("../support/bibliography_multi_same_page_late_change_included_body_baseline_helpers.rs");
include!("bibliography_multi_same_page_late_change_included_body_baseline.rs");
include!("bibliography_multi_same_page_late_change_included_body_sibling_dirty_orders.rs");
include!("bibliography_multi_same_page_late_change_included_body_sibling_interleaved.rs");
include!("bibliography_multi_same_page_late_change_included_body_tail_noise.rs");
