include!("bibliography_multi_rebuild_trailing_input_included_body_sibling_ordering_baseline_baseline.rs");
include!("bibliography_multi_rebuild_trailing_input_included_body_sibling_ordering_baseline_reversed_dirty_order.rs");
