smoke_case_test!(
    internal_compiler_rebuilds_from_base_snapshot_for_semantic_multi_bibliography_edit_even_with_later_tracked_toplevel_change_when_unchanged_sibling_bibliography_is_also_dirty_with_interleaved_dirty_order_and_untracked_dirty_file_follows,
    run_rev5_top_case(Rev5TopCase::SiblingInterleavedUntrackedFollows)
);
