smoke_case_test!(
    internal_compiler_still_replays_earlier_toplevel_checkpoint_when_untracked_dirty_file_precedes_semantically_equal_same_page_multi_bibliography_edit,
    run_same_page_top_cp_case(SamePageTopCpCase::UntrackedPrecedes)
);
