smoke_case_test!(
    internal_compiler_rebuilds_from_base_for_late_multi_bibliography_semantic_change_with_included_body_when_untracked_dirty_file_precedes,
    run_late_multi_included_body_case(LateMultiIncludedBodyCase::UntrackedPrecedes)
);
