include!("bibliography_multi_same_page_trailing_input_included_body_baseline_baseline_reversed_and_follows_baseline_and_reversed.rs");

include!("bibliography_multi_same_page_trailing_input_included_body_baseline_baseline_reversed_and_follows_untracked_follows.rs");
