smoke_case_test!(
    internal_compiler_falls_back_to_preamble_replay_when_semantically_equal_bibliography_edit_with_included_body_is_followed_by_untracked_dirty_file,
    run_body_sem_eq_case(BodySemEqCase::UntrackedFollows)
);
