smoke!(internal_compiler_falls_back_to_preamble_replay_when_late_input_edit_is_followed_by_unreadable_dirty_file => run_boundary_late_input_noise_case(BoundaryLateInputNoiseCase::UnreadableFollows));
