smoke_case_test!(
    internal_compiler_rebuilds_from_base_when_late_input_is_removed_with_retained_file_also_dirty_and_unreadable_dirty_file_follows,
    run_late_input_removal_case(LateInputRemovalCase::RetainedDirtyUnreadableFollows)
);
