include!("unchanged_tail_noop_leading_toplevel_variants_multi_input_interleaved_orders_primary.rs");
include!("unchanged_tail_noop_leading_toplevel_variants_multi_input_interleaved_orders_other.rs");
