smoke_case_test!(
    internal_compiler_reuses_full_unchanged_tail_for_nonrendering_multi_input_and_leading_toplevel_edits_with_other_interleaved_dirty_order_and_unreadable_dirty_file_follows,
    run_leading_noise_case(LeadingNoiseCase::OtherInterleavedUnreadableFollows)
);
