include!("unchanged_tail_noop_leading_toplevel_variants_multi_input_dirty_orders.rs");
include!("unchanged_tail_noop_leading_toplevel_variants_multi_input_interleaved_orders.rs");
include!("unchanged_tail_noop_leading_toplevel_variants_mixed_multi_input_dirty_orders.rs");
include!("unchanged_tail_noop_leading_toplevel_variants_mixed_multi_input_interleaved_orders.rs");
