smoke_case_test!(
    internal_compiler_reuses_full_unchanged_tail_for_nonrendering_multi_input_and_toplevel_edits_with_reversed_dirty_order_and_untracked_dirty_file_precedes_it,
    run_trailing_noise_case(TrailingNoiseCase::ReversedUntrackedPrecedes)
);
