smoke_case_test!(
    internal_compiler_reuses_full_unchanged_tail_for_nonrendering_trailing_toplevel_and_mixed_multi_input_edits_with_other_interleaved_dirty_order,
    run_multi_mix_case(MultiMixCase::OtherInterleavedDirtyOrder)
);
