smoke_case_test!(
    internal_compiler_reuses_full_unchanged_tail_for_nonrendering_mixed_toplevel_and_multi_input_edits_with_other_interleaved_dirty_order_and_unreadable_dirty_file_follows,
    run_mixed_top_other_inter_case(MixedTopOtherInterCase::UnreadableFollows)
);
