smoke_case_test!(
    internal_compiler_reuses_full_unchanged_tail_for_nonrendering_double_leading_edits_with_reversed_dirty_order_and_untracked_dirty_file_follows,
    run_order_double_case(OrderDoubleCase::UntrackedFollows)
);
