smoke_case_test!(
    internal_compiler_reuses_full_unchanged_tail_for_nonrendering_double_leading_edits_with_other_interleaved_dirty_order_and_untracked_dirty_file_between_them,
    run_order_double_other_case(OrderDoubleOtherCase::Untracked)
);
