use tex_render_model::CaptionKind;
use tex_tokens::Token;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum Meaning {
    Macro(MacroDefinition),
    Primitive(Primitive),
    Token(Token),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct MacroDefinition {
    pub(crate) parameter_count: u8,
    pub(crate) optional_first_argument_default: Option<Vec<Token>>,
    pub(crate) body: Vec<Token>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct ReferenceCommand {
    pub(crate) canonical_name: &'static str,
    pub(crate) key_argument_count: u8,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct LinkCommand {
    pub(crate) canonical_name: &'static str,
    pub(crate) has_separate_text_argument: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct HeadingCommand {
    pub(crate) canonical_name: &'static str,
    pub(crate) level: u8,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct CaptionCommand {
    pub(crate) canonical_name: &'static str,
    pub(crate) fixed_kind: Option<CaptionKind>,
    pub(crate) reads_kind_argument: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct GraphicCommand {
    pub(crate) canonical_name: &'static str,
    pub(crate) include_pdf: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Primitive {
    Relax,
    Par,
    LegacyMathWordBoundary,
    LegacyTextScriptBoundary,
    Def,
    GlobalDef,
    ExpandedDef,
    GlobalExpandedDef,
    Let,
    FutureLet,
    String,
    Immediate,
    Protect,
    NewRead,
    OpenIn,
    CloseIn,
    Read,
    ReadLine,
    NewWrite,
    OpenOut,
    CloseOut,
    Write,
    ProtectedWrite,
    IgnoreSpaces,
    JobName,
    CurrentModuleName,
    CurrentModuleExt,
    CurrentModulePath,
    FilenameParse,
    Meaning,
    Detokenize,
    StripPrefix,
    TextWrapper,
    Uppercase,
    Lowercase,
    ExpandAfter,
    ExpandedTokens,
    Unexpanded,
    CsName,
    EndCsName,
    BeginEnvironment,
    EndEnvironment,
    Item,
    BeginGroupCommand,
    EndGroupCommand,
    AfterGroup,
    AfterAssignment,
    Long,
    Protected,
    Outer,
    Global,
    Unless,
    MakeAtLetter,
    MakeAtOther,
    IfTrue,
    IfFalse,
    NewIf,
    CharDef,
    CatCode,
    NeedsTeXFormat,
    ProvidesFile,
    ProvidesPackage,
    ProvidesClass,
    DocumentClass,
    LoadClass,
    LoadClassWithOptions,
    RequirePackage,
    UsePackage,
    RequirePackageWithOptions,
    PassOptionsToClass,
    PassOptionsToPackage,
    DeclareOption,
    ExecuteOptions,
    ProcessOptions,
    AtBeginDocument,
    AtEndDocument,
    AtEndOfPackage,
    AtEndOfClass,
    Message,
    Typeout,
    WriteLog,
    NewCount,
    CountDef,
    NewDimen,
    DimenDef,
    NewSkip,
    SkipDef,
    SetCounter,
    AddToCounter,
    StepCounter,
    RefStepCounter,
    AddToReset,
    RemoveFromReset,
    NewLength,
    SetLength,
    AddToLength,
    NewToks,
    ToksDef,
    NewCommand,
    DeclareRobustCommand,
    RenewCommand,
    ProvideCommand,
    DeclareMathOperator,
    PackageInfo,
    PackageInfoNoLine,
    ClassInfo,
    ClassInfoNoLine,
    PackageWarning,
    PackageWarningNoLine,
    ClassWarning,
    ClassWarningNoLine,
    PackageError,
    ClassError,
    GenericInfo,
    GenericWarning,
    GenericError,
    ErrMessage,
    LatexInfo,
    LatexWarning,
    LatexWarningNoLine,
    LatexError,
    IfPackageLoadedTF,
    IfClassLoadedTF,
    IfPackageAtLeastTF,
    IfClassAtLeastTF,
    IfPackageLater,
    IfClassLater,
    IfPackageWith,
    IfClassWith,
    IfEof,
    IfFileExists,
    InputIfFileExists,
    AtInput,
    OnlyPreamble,
    OneLevelSanitize,
    BspHack,
    Esphack,
    InAt,
    IfInAt,
    TempSwaTrue,
    TempSwaFalse,
    IfTempSwa,
    FileswTrue,
    FileswFalse,
    IfFilesw,
    NoFiles,
    Loop,
    For,
    WhileNum,
    WhileSw,
    IfCsName,
    IfDefined,
    IfUndefined,
    IfDefinable,
    IfNextChar,
    IfStar,
    IfEmpty,
    IfNotEmpty,
    IfMtArg,
    IfNotMtArg,
    TestOpt,
    DblArg,
    Car,
    Cdr,
    TFor,
    Cons,
    RemoveElement,
    ThirdOfThree,
    ExpandTwoArgs,
    ZapSpace,
    FirstOfOne,
    Iden,
    FirstOfTwo,
    SecondOfTwo,
    Gobble,
    GobbleTwo,
    GobbleThree,
    GobbleFour,
    GAddToMacro,
    NameDef,
    NameXDef,
    NameUse,
    Advance,
    Multiply,
    Divide,
    IfChar,
    IfOdd,
    IfCat,
    IfCase,
    IfX,
    IfNum,
    IfDim,
    Else,
    Fi,
    Count,
    Dimen,
    Skip,
    Toks,
    Value,
    The,
    Number,
    RomanNumeral,
    CounterArabic,
    CounterRoman,
    CounterRomanUpper,
    CounterAlph,
    CounterAlphUpper,
    EndInput,
    Input,
    Include,
    IncludeOnly,
    Citation,
    Reference(ReferenceCommand),
    Link(LinkCommand),
    Heading(HeadingCommand),
    Caption(CaptionCommand),
    Graphic(GraphicCommand),
    GraphicPath,
    DeclareGraphicsExtensions,
    SetKeys,
}
